### ISSUE TITLE
read_*_postgis functions can only be used with trackintel conform databases

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#277]
In practice, most databases are not trackintel conform. However, the `read_*_postgis` can only be used with these functions. The reason is that they are passing the result from the query to the `read_*_gpd` functions but without allowing to specify the `mapper` keywords. This makes these functions difficult to use in practice. 
A simple solution would be to allow to pass parameters of the `read_*_gpd` function.

**Comment by henrymartin1** [comment]
I have noticed another error. If I have timestamp aware data in the database and I use the `read_staypoints_postgis` function than I get the following error: 
```
C:\ProgramData\Anaconda3\envs\graph_rep\lib\site-packages\trackintel\io\file.py:571: UserWarning: Assuming UTC timezone for column started_at
  warnings.warn("Assuming UTC timezone for column {}".format(col_name))
Traceback (most recent call last):
  [...]
   line 42, in <module>
    sp = ti.io.read_staypoints_postgis(sql="select * from {}.staypoints".format(study), con=engine, geom_col='geom')
  File "C:\ProgramData\Anaconda3\envs\graph_rep\lib\site-packages\trackintel\io\postgis.py", line 22, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\graph_rep\lib\site-packages\trackintel\io\postgis.py", line 165, in read_staypoints_postgis
    return ti.io.read_staypoints_gpd(spts, geom_col=geom_col)
  File "C:\ProgramData\Anaconda3\envs\graph_rep\lib\site-packages\trackintel\io\from_geopandas.py", line 106, in read_staypoints_gpd
    stps[col] = _localize_timestamp(dt_series=stps[col], pytz_tzinfo=tz, col_name=col)
  File "C:\ProgramData\Anaconda3\envs\graph_rep\lib\site-packages\trackintel\io\file.py", line 575, in _localize_timestamp
    return dt_series.apply(pd.Timestamp, tz=timezone)
  File "C:\ProgramData\Anaconda3\envs\graph_rep\lib\site-packages\pandas\core\series.py", line 4356, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "C:\ProgramData\Anaconda3\envs\graph_rep\lib\site-packages\pandas\core\apply.py", line 1036, in apply
    return self.apply_standard()
  File "C:\ProgramData\Anaconda3\envs\graph_rep\lib\site-packages\pandas\core\apply.py", line 1092, in apply_standard
    mapped = lib.map_infer(
  File "pandas\_libs\lib.pyx", line 2859, in pandas._libs.lib.map_infer
  File "C:\ProgramData\Anaconda3\envs\graph_rep\lib\site-packages\pandas\core\apply.py", line 131, in f
    return func(x, *args, **kwargs)
  File "pandas\_libs\tslibs\timestamps.pyx", line 1328, in pandas._libs.tslibs.timestamps.Timestamp.__new__
ValueError: Cannot pass a datetime or Timestamp with tzinfo with the tz parameter. Use tz_convert instead.
```
Maybe this could be solved with passing something different as input to the tz argument of `read_staypoints_gpd` but I am not sure at the moment
