### ISSUE TITLE
Test on Windows are failing

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#456]
Not sure yet what this is about:

```
In a future release, GeoPandas will switch to using Shapely by default. If you are using PyGEOS directly (calling PyGEOS functions on geometries from GeoPandas), this will then stop working and you are encouraged to migrate from PyGEOS to Shapely 2.0 (https://shapely.readthedocs.io/en/latest/migration_pygeos.html).
  import geopandas as gpd
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\a\trackintel\trackintel\trackintel\__init__.py", line 1, in <module>
    import trackintel.model
  File "D:\a\trackintel\trackintel\trackintel\model\__init__.py", line 1, in <module>
    from .positionfixes import PositionfixesAccessor
  File "D:\a\trackintel\trackintel\trackintel\model\positionfixes.py", line 8, in <module>
    from trackintel.visualization.positionfixes import plot_positionfixes
  File "D:\a\trackintel\trackintel\trackintel\visualization\__init__.py", line 1, in <module>
    from .locations import plot_locations
  File "D:\a\trackintel\trackintel\trackintel\visualization\locations.py", line 6, in <module>
    from trackintel.visualization.osm import plot_osm_streets
  File "D:\a\trackintel\trackintel\trackintel\visualization\osm.py", line 3, in <module>
    import osmnx as ox
  File "C:\Miniconda3\envs\test\lib\site-packages\osmnx\__init__.py", line 3, in <module>
    from ._api import *
  File "C:\Miniconda3\envs\test\lib\site-packages\osmnx\_api.py", line 17, in <module>
    from .geometries import geometries_from_address
  File "C:\Miniconda3\envs\test\lib\site-packages\osmnx\geometries.py", line 21, in <module>
    from shapely.geos import TopologicalError
ImportError: cannot import name 'TopologicalError' from 'shapely.geos' (C:\Miniconda3\envs\test\lib\site-packages\shapely\geos.py)
Error: Process completed with exit code 1.
```

https://github.com/mie-lab/trackintel/actions/runs/3679511054/jobs/6224048994

**Comment by bifbof** [comment]
So far we imported pygeos as extra dependency. Now they incorporated pygeos into shapely breaking some of our code (probably mine).

**Comment by henrymartin1** [comment]
It seems the bug is caused by osmnx which is not compatible with shapely 2.0. I could fix it by setting the requirements to shapely <= 1.8.5 in the environment. 
So I guess for now the solution is that we set this requirement until shapely is compatible.

**Comment by hong2223** [comment]
I encountered this error again when installing trackintel with conda `conda install trackintel`. I guess its related to the shapely and osmnx compatibility issue. Now v1.3.0 OSMnx supports v2.0 Shapely, so we should delete the shapely requirements in our environment.
