### ISSUE TITLE
Positionfix aggregation by tripleg id fails if user_id is a string

### ISSUE THREAD

**Issue by void-rooster** [mie-lab/trackintel#514]
The following minimal working example triggers an exception in `generate_triplegs` because `user_id` cannot be aggregated with the `mean` method:

```python
import pandas as pd
import geopandas as gpd
import pandas as pd
from trackintel.preprocessing.positionfixes import (
    generate_staypoints,
    generate_triplegs,
)
from trackintel.preprocessing.staypoints import generate_locations


positionfixes = gpd.GeoDataFrame(
    {
        "user_id": "test",
        "tracked_at": pd.date_range("2023-01-01T00:00:00Z", freq="60s", periods=10),
    },
    geometry=gpd.points_from_xy([0] * 5 + [1] * 5, [0] * 5 + [1] * 5),
    crs="EPSG:4326",
)

positionfixes, staypoints = generate_staypoints(positionfixes)
staypoints, _ = generate_locations(staypoints)
positionfixes, triplegs = generate_triplegs(positionfixes)
```
Traceback:
```python
Traceback (most recent call last):
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/groupby/groupby.py", line 1490, in array_func
    result = self.grouper._cython_operation(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/groupby/ops.py", line 959, in _cython_operation
    return cy_op.cython_operation(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/groupby/ops.py", line 657, in cython_operation
    return self._cython_op_ndim_compat(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/groupby/ops.py", line 482, in _cython_op_ndim_compat
    res = self._call_cython_op(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/groupby/ops.py", line 541, in _call_cython_op
    func = self._get_cython_function(self.kind, self.how, values.dtype, is_numeric)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/groupby/ops.py", line 173, in _get_cython_function
    raise NotImplementedError(
NotImplementedError: function is not implemented for this dtype: [how->mean,dtype->object]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/nanops.py", line 1692, in _ensure_numeric
    x = float(x)
        ^^^^^^^^
ValueError: could not convert string to float: 'testtesttesttesttest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/nanops.py", line 1696, in _ensure_numeric
    x = complex(x)
        ^^^^^^^^^^
ValueError: complex() arg is a malformed string

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kpenner/dev/trackintel/test.py", line 12, in <module>
    positionfixes, triplegs = generate_triplegs(positionfixes)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/trackintel/preprocessing/positionfixes.py", line 364, in generate_triplegs
    tpls = posfix_grouper.agg(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/groupby/generic.py", line 1269, in aggregate
    result = op.agg()
             ^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/apply.py", line 163, in agg
    return self.agg_dict_like()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/apply.py", line 420, in agg_dict_like
    results = {
              ^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/apply.py", line 421, in <dictcomp>
    key: obj._gotitem(key, ndim=1).agg(how) for key, how in arg.items()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/groupby/generic.py", line 238, in aggregate
    ret = self._aggregate_multiple_funcs(func, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/groupby/generic.py", line 316, in _aggregate_multiple_funcs
    results[key] = self.aggregate(func, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/groupby/generic.py", line 232, in aggregate
    return getattr(self, func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/groupby/groupby.py", line 1855, in mean
    result = self._cython_agg_general(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/groupby/groupby.py", line 1507, in _cython_agg_general
    new_mgr = data.grouped_reduce(array_func)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/internals/base.py", line 197, in grouped_reduce
    res = func(arr)
          ^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/groupby/groupby.py", line 1503, in array_func
    result = self._agg_py_fallback(values, ndim=data.ndim, alt=alt)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/groupby/groupby.py", line 1457, in _agg_py_fallback
    res_values = self.grouper.agg_series(ser, alt, preserve_dtype=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/groupby/ops.py", line 994, in agg_series
    result = self._aggregate_series_pure_python(obj, func)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/groupby/ops.py", line 1015, in _aggregate_series_pure_python
    res = func(group)
          ^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/groupby/groupby.py", line 1857, in <lambda>
    alt=lambda x: Series(x).mean(numeric_only=numeric_only),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/generic.py", line 11556, in mean
    return NDFrame.mean(self, axis, skipna, numeric_only, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/generic.py", line 11201, in mean
    return self._stat_function(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/generic.py", line 11158, in _stat_function
    return self._reduce(
           ^^^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/series.py", line 4670, in _reduce
    return op(delegate, skipna=skipna, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/nanops.py", line 96, in _f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/nanops.py", line 158, in f
    result = alt(values, axis=axis, skipna=skipna, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/nanops.py", line 421, in new_func
    result = func(values, axis=axis, skipna=skipna, mask=mask, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/nanops.py", line 727, in nanmean
    the_sum = _ensure_numeric(values.sum(axis, dtype=dtype_sum))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kpenner/mambaforge/envs/trackintel/lib/python3.11/site-packages/pandas/core/nanops.py", line 1699, in _ensure_numeric
    raise TypeError(f"Could not convert {x} to numeric") from err
TypeError: Could not convert testtesttesttesttest to numeric
```

https://github.com/mie-lab/trackintel/blob/11c36f3b2567b2d1c012e284ee3f89b5723caea0/trackintel/preprocessing/positionfixes.py#L364

**Comment by bifbof** [comment]
Thank you for the good bug report. :)
This one will be fixed in #516.
